
/*
PROYECTO FINAL MASCOTAS
Nota: Estas tablas son de un solo esquema de base de datos,
deberás realizar el ajuste necesario para que cumplan con la 
característica de una Arquitectura de Microservicios.


*/

CREATE TABLE MASCOTAS (
    ID_MASCOTA NUMBER,
    NOMBRE NVARCHAR2(15),
    RAZA NVARCHAR2(15),
    EDAD NUMBER,
    RAZON_CITA NVARCHAR2(100),
    CLIENTE_ID NUMBER,
    RESPONSABLE_ID NUMBER,
    VETERINARIA_ID NUMBER,

    CONSTRAINT PK_MASCOTAS PRIMARY KEY (ID_MASCOTA),
    CONSTRAINT FK_CLIENTE_ID FOREIGN KEY (CLIENTE_ID) 
    REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT FK_RESPONSABLE_ID FOREIGN KEY (RESPONSABLE_ID) 
    REFERENCES RESPONSABLES(ID_RESPONSABLE),
    CONSTRAINT FK_VETERINARIA_ID FOREIGN KEY (VETERINARIA_ID) 
    REFERENCES VETERINARIAS(ID_VETERINARIA)
);

CREATE SEQUENCE SEQ_MASCOTAS 
START WITH 1 
INCREMENT BY 1 
NOCACHE 
NOCYCLE;

DESC MASCOTAS;
ALTER TABLE MASCOTAS ADD CLIENTE_ID NUMBER;

ALTER TABLE MASCOTAS ADD CONSTRAINT FK_CLIENTE_ID 
FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID_CLIENTE);
ALTER TABLE MASCOTAS ADD VETERINARIA_ID NUMBER;
ALTER TABLE MASCOTAS ADD CONSTRAINT FK_VETERINARIA_ID
FOREIGN KEY (VETERINARIA_ID) REFERENCES VETERINARIAS(ID_VETERINARIA);

SELECT * FROM VETERINARIAS WHERE ID_VETERINARIA = 1;
ALTER TABLE MASCOTAS DROP CONSTRAINT FK_VETERINARIA_ID;






