
/*
PROYECTO FINAL RESPONSABLES
Nota: Estas tablas son de un solo esquema de base de datos, deberás realizar 
el ajuste necesario para que cumplan con la característica de una Arquitectura de Microservicios.

*/

CREATE TABLE RESPONSABLES (
    ID_RESPONSABLE NUMBER,
    NOMBRE NVARCHAR2(50),
    CONTACTO NUMBER,
    VETERINARIA_ID NUMBER,
    CONSTRAINT PK_RESPONSABLES PRIMARY KEY (ID_RESPONSABLE),
    CONSTRAINT FK_RESPONSABLE_VETERINARIA FOREIGN KEY (VETERINARIA_ID) 
REFERENCES VETERINARIAS(ID_VETERINARIA)
);


CREATE SEQUENCE SEQ_RESPONSABLES 
START WITH 1 
INCREMENT BY 1 
NOCACHE 
NOCYCLE;


